/* task3.c */
suit naipe(wchar_t card);
value valor(wchar_t card);
int checkCode(const void *a, const void *b);
combination setOfCards(card cards[], int size);
combination sequence(card cards[], int size);
combination doubleSequence(card cards[], int size);
int check_combination(card temp[], int size);
int contains_all(const wchar_t *base, const wchar_t *object);
void sort_strings(wchar_t string[], int size);
void removerSubstring(wchar_t *string, const wchar_t *substring);
int validPlay(wchar_t play_string[], int size);
void isValid(wchar_t deck_string[], wchar_t play_string[], card deck[], int size);
int sumCards(card hand1[], card hand2[], int size, int size2);
int kingException(card deck[], int size, card play[], int size2, card actual_play[], int size3, wchar_t deck_string[], wchar_t actual_play_string[]);
void organize(wchar_t deck_string[], int size, wchar_t actual_play_string[], int size3, card actual_play[], card play[], int size2);
void processInput(wchar_t actual_play_string[], card actual_play[], wchar_t play_string[], int size2, card play[]);
void process(int size3, card actual_play[], wchar_t actual_play_string[], card play[], wchar_t play_string[], int size2);
void printDeckCodes(card deck[], int size);
void space(int sizeop, int control);
void package(int size3, card actual_play[], wchar_t actual_play_string[], card play[], wchar_t play_string[], int size, wchar_t deck_string[], int size2);
int comb(card play[], int size2, card actual_play[], int size3);
void process_print(int sizeop, card deck[], wchar_t deck_string[]);
int all_King(card play[], int size);
void newDeck(wchar_t deck_string[], int size, wchar_t play_string[], int size2, card deck[]);
int all_equal(int arr[], int size);
int find_Card(wchar_t *strings[], wchar_t result[]);
void isValid2(wchar_t deck_string[], wchar_t *last_plays[], card deck[], int size);
void readDeck(wchar_t *deck_string, card *deck, int deck_size);
void processPlays(wchar_t *deck_string, int plays, card *deck, int deck_size);
void processMaxPlays(wchar_t *deck_string, int plays, wchar_t **last_plays, card *deck, int deck_size);
void processTest(wchar_t *deck_string, int plays, wchar_t **last_plays, int deck_size);
int main(void);
