-- MySQL Script generated by MySQL Workbench
-- Thu May  1 15:58:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jbvmotors
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jbvmotors` ;

-- -----------------------------------------------------
-- Schema jbvmotors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jbvmotors` DEFAULT CHARACTER SET utf8 ;
USE `jbvmotors` ;

-- -----------------------------------------------------
-- Table `jbvmotors`.`Aluguer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Aluguer` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Aluguer` (
  `id_aluguer` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NOT NULL,
  `data_termino` DATETIME NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `obs` TEXT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_veiculo` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_aluguer`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_veiculo_idx` (`id_veiculo` ASC) VISIBLE,
  INDEX `id_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `jbvmotors`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_veiculo`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `jbvmotors`.`Veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `jbvmotors`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `nif` INT NOT NULL,
  `nic` INT NOT NULL,
  `contacto` VARCHAR(31) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Fatura` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Fatura` (
  `id_aluguer` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(10) NOT NULL,
  `data_emissao` DATETIME NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `met_pagamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_aluguer`),
  INDEX `id_aluguer_idx` (`id_aluguer` ASC) VISIBLE,
  CONSTRAINT `fk_id_aluguer`
    FOREIGN KEY (`id_aluguer`)
    REFERENCES `jbvmotors`.`Aluguer` (`id_aluguer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `contacto` VARCHAR(31) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `horario` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `nif` INT NOT NULL,
  `nss` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `id_stand` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `id_stand_idx` (`id_stand` ASC) VISIBLE,
  CONSTRAINT `fk_id_stand_funcionario`
    FOREIGN KEY (`id_stand`)
    REFERENCES `jbvmotors`.`Stand` (`id_stand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Licencas_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Licencas_Cliente` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Licencas_Cliente` (
  `id_licenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(48) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_licenca`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_id_cliente_licencas`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `jbvmotors`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Licencas_Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Licencas_Funcionario` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Licencas_Funcionario` (
  `id_licenca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(48) NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_licenca`),
  INDEX `id_funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_id_funcionario_licencas`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `jbvmotors`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Stand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Stand` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Stand` (
  `id_stand` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `contacto` VARCHAR(31) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbvmotors`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jbvmotors`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `jbvmotors`.`Veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(120) NOT NULL,
  `ano` INT NOT NULL,
  `matricula` CHAR(6) NOT NULL,
  `cor` VARCHAR(30) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `quilometragem` INT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `obs` TEXT NULL,
  `id_stand` INT NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `id_stand_idx` (`id_stand` ASC) VISIBLE,
  CONSTRAINT `fk_id_stand_veiculo`
    FOREIGN KEY (`id_stand`)
    REFERENCES `jbvmotors`.`Stand` (`id_stand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;